spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: SpiralStaircase
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrapServers: localhost:29092

application:
  security:
    jwt:
      secretKey: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 0

