spring:
  application:
    name: stock-service
  datasource:
    url: jdbc:postgresql://localhost:5434/stock-service
    username: postgres
    password: SpiralStaircase
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    appName: stock-info-service
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints.web.exposure.include:
    - '*'
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true

endpoints:
  health:
    enabled:
      nodeValue: 'true'
      sensitive: 'false'
  enabled: 'false'

resilience4j:
  circuitbreaker:
    instances:
      default:
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        failureRateThreshold: '50'
        slidingWindowType: COUNT_BASED
        event-consumer-buffer-size: '10'
        registerHealthIndicator: 'true'
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: '3'
        slidingWindowSize: '5'
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s
  retry:
    instances:
      inventory:
        wait-duration: 5s
        max-attempts: '3'

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
      isolation:
        thread:
          timeoutInMilliseconds: 160000000

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
server:
  port: 7777
